### ISSUE TITLE
Pseudonymisation with gICS

### ISSUE THREAD

**Issue by TimoFuchsUKR** [samply/adt2fhir#13]
Hi,
is there a pseudonymisation with gICS (https://www.ths-greifswald.de/forscher/gics/) planned?
Should be very similar to the pseudonymisation with the Mainzelliste.

Greetings from Regensburg
Timo

**Comment by PierreDelpy** [comment]
Hello Timo,

sorry for the late reply.
Pseudonymisation with gPAS would be feasible, however I won't have time to add this feature in the near future.
Patient consents covered by gICS are not part of ADT GEKID. Therefore, there will be no gICS integration.

Greetings from Heidelberg
Pierre
