### ISSUE TITLE
Wrong LOINC code

### ISSUE THREAD

**Issue by jschlad** [samply/adt2fhir#14]
Hello,

the LOINC code in https://github.com/samply/adt2fhir/blob/6e6eb10070cfdac8b5b1090a7b8c670b943da203/src/main/resources/MDS2FHIR.xsl#L1104 seems to be invalid because of a typo. Instead of '201906-3' the correct code would be '21906-3'

Greetings from Lübeck

**Comment by PierreDelpy** [comment]
Hello,

thank you for pointing that out.
I just fixed it (https://github.com/samply/adt2fhir/pull/19).

Greetings from Heidelberg
